// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	model "ilanver/internal/model"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	repository "ilanver/internal/repository"

	testing "testing"
)

// IUserRepo is an autogenerated mock type for the IUserRepo type
type IUserRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *IUserRepo) Get(id uint) (model.User, error) {
	ret := _m.Called(id)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(uint) model.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPhone provides a mock function with given fields: phone
func (_m *IUserRepo) GetByPhone(phone string) (model.User, error) {
	ret := _m.Called(phone)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(phone)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: phone
func (_m *IUserRepo) Login(phone string) (model.User, error) {
	ret := _m.Called(phone)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(phone)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: user
func (_m *IUserRepo) Save(user *model.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: user
func (_m *IUserRepo) Update(user *model.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: db
func (_m *IUserRepo) WithTx(db *gorm.DB) repository.IUserRepo {
	ret := _m.Called(db)

	var r0 repository.IUserRepo
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.IUserRepo); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.IUserRepo)
		}
	}

	return r0
}

// NewIUserRepo creates a new instance of IUserRepo. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserRepo(t testing.TB) *IUserRepo {
	mock := &IUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
